<?php

namespace Projet\StatisfootBundle\Repository;

/**
 * joueurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class joueurRepository extends \Doctrine\ORM\EntityRepository
{
}
