<?php

namespace Projet\StatisfootBundle\Repository;

/**
 * managerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class managerRepository extends \Doctrine\ORM\EntityRepository
{
}
