<?php

namespace Projet\StatisfootBundle\Repository;

/**
 * type_actionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class type_actionRepository extends \Doctrine\ORM\EntityRepository
{
}
