<?php

namespace Projet\StatisfootBundle\Repository;

/**
 * type_butRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class type_butRepository extends \Doctrine\ORM\EntityRepository
{
}
