<?php

namespace Projet\StatisfootBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * butRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class butRepository extends EntityRepository
{
	//recupération des buts marqués par un joueur dans une compétitions donnée
	public function findBut_compet($id_joueur,$id_compet){
		$qb = $this->createQueryBuilder('b')
			->leftJoin('b.match_foot','match')
			->leftJoin('b.joueur','j')
			->leftJoin('match.competition','compet')
			->where('j.id = :idJ')
			->andWhere('compet.id = :idC')
			->setParameter('idJ',$id_joueur)
			->setParameter('idC',$id_compet);
		
		return $qb->getQuery()->getResult();
	}

	//recupération des buts marqués dans une compétitions donnée
	public function findButCompet($idC){
		$qb = $this->createQueryBuilder('b')
			->leftJoin('b.match_foot','match')
			->leftJoin('b.joueur','j')
			->leftJoin('match.competition','compet')
			->addSelect('j')
			->where('compet.id = :idC')
			->setParameter('idC',$idC);
		
		return $qb->getQuery()->getResult();
	}

	//recuperation du dernier but d'un match
	public function findDernierButMatch($idM){
		$qb = $this->createQueryBuilder('b')
			->leftJoin('b.match_foot','match')
			->where('match.id = :id')
			->setParameter('id',$idM)
			->orderBy('b.id','DESC')
			->setMaxResults('1');
		
		return $qb->getQuery()->getResult();
	}
}
