<?php

namespace Projet\StatisfootBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * butRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class butRepository extends EntityRepository
{
	public function findBut_compet($id_joueur,$id_compet){
		$qb = $this->createQueryBuilder('b')
			->leftJoin('b.match_foot','match')
			->leftJoin('b.joueur','j')
			->leftJoin('match.competition','compet')
			->where('j.id = :idJ')
			->andWhere('compet.id = :idC')
			->setParameter('idJ',$id_joueur)
			->setParameter('idC',$id_compet);
		
		return $qb->getQuery()->getResult();
	}
}
