<?php

namespace Projet\StatisfootBundle\Repository;

/**
 * competitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class competitionRepository extends \Doctrine\ORM\EntityRepository
{
}
