<?php

namespace Projet\StatisfootBundle\Repository;

/**
 * equipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class equipeRepository extends \Doctrine\ORM\EntityRepository
{
	public function findEquipes($idC){
		$qb = $this->createQueryBuilder('e')
			->leftJoin('e.club','c')
			->leftJoin('e.niveau','n')
			->addSelect('n')
			->where('c.id = :id')
			->setParameter('id', $idC);

		return $qb->getQuery()->getResult();
	}
}
