<?php

namespace Projet\StatisfootBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * equipe_managerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class equipe_managerRepository extends EntityRepository
{
	public function findEquipeByManager($idM){
		$qb = $this->createQueryBuilder('meq')
			->leftJoin('meq.equipe','eq')
			->leftJoin('meq.manager','ma')
			->addSelect('eq')
			->where('meq.dateFin > :date')
			->andWhere('ma.id = :id')
			->setParameter('date', new \DateTIME())
			->setParameter('id', $idM);

		return $qb->getQuery()->getResult();
	}
}
