<?php

namespace Projet\StatisfootBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * joueur_equipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class joueur_equipeRepository extends EntityRepository
{
	public function findJoueurs($id){
		$qb = $this->createQueryBuilder('j')
			->leftJoin('j.equipe','eq')
			->addSelect('eq')
			->leftJoin('j.joueur','joue')
			->addSelect('joue')
			->where('j.date_fin > :date')
			->andWhere('eq.id = :id')
			->setParameter('date', new \DateTIME())
			->setParameter('id', $id);

		return $qb->getQuery()->getResult();
	}

	public function find_equipe($id_joueur){
		$qb = $this->createQueryBuilder('j')
			->leftJoin('j.equipe','eq')
			->leftJoin('j.joueur','joue')
			->leftJoin('eq')
			->where('j.date_fin > :date')
			->andWhere('j.id = :id')
			->andWhere()
			->setParameter('date', new \DateTIME())
			->setParameter('id', $id);

		return $qb->getQuery()->getResult();
	}
}
