<?php

namespace Projet\StatisfootBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * joueurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class joueurRepository extends EntityRepository
{
	
}
