<?php

namespace Projet\StatisfootBundle\Repository;

/**
 * match_footRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class match_footRepository extends \Doctrine\ORM\EntityRepository
{
}
