<?php

namespace Projet\StatisfootBundle\Repository;

/**
 * match_joueurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class match_joueurRepository extends \Doctrine\ORM\EntityRepository
{
}
