<?php

namespace Projet\StatisfootBundle\Repository;

/**
 * niveauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class niveauRepository extends \Doctrine\ORM\EntityRepository
{
}
