<?php

namespace Projet\StatisfootBundle\Repository;

/**
 * passe_decisiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class passe_decisiveRepository extends \Doctrine\ORM\EntityRepository
{
}
