<?php

namespace Projet\StatisfootBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * passe_decisiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class passe_decisiveRepository extends EntityRepository
{
	public function findPasse_compet($id_joueur,$id_compet){
		$qb = $this->createQueryBuilder('p')
			->leftJoin('p.but','b')
			->leftJoin('b.match_foot','match')
			->leftJoin('p.joueur','j')
			->leftJoin('match.competition','compet')
			->where('j.id = :idJ')
			->andWhere('compet.id = :idC')
			->setParameter('idJ',$id_joueur)
			->setParameter('idC',$id_compet);
		
		return $qb->getQuery()->getResult();
	}

	public function findPasseJoueurMatch($idM,$idJ){
		$qb = $this->createQueryBuilder('p')
			->leftJoin('p.but','b')
			->leftJoin('b.match_foot','match')
			->leftJoin('p.joueur','j')
			->select('COUNT(p.id) AS nbp')
			->where('j.id = :idJ')
			->andWhere('match.id = :idM')
			->setParameter('idJ',$idJ)
			->setParameter('idM',$idM);
		
		return $qb->getQuery()->getResult();
	}
}
