<?php

namespace Projet\StatisfootBundle\Repository;

/**
 * syst_jeu_defRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class syst_jeu_defRepository extends \Doctrine\ORM\EntityRepository
{
}
