statisfoot_accueil:
    path:     /
    defaults: 
        _controller: ProjetStatisfootBundle:Match:index

statisfoot_accueil_date:
    path:     /{date}
    defaults: 
        _controller: ProjetStatisfootBundle:Match:indexDate
    requirements:
        date: \d{10}

statisfoot_match:
    path:     /match/{id}
    defaults: 
        _controller: ProjetStatisfootBundle:Match:match_foot 
    requirements:
        id: \d+

statisfoot_club:
    path:     /club/{id}
    defaults: 
        _controller: ProjetStatisfootBundle:Equipe:club

statisfoot_liste_equipe:
    path:     /listeEquipe
    defaults: 
        _controller: ProjetStatisfootBundle:Equipe:listequipe

statisfoot_equipe:
    path:     /equipe/{id}
    defaults: 
        _controller: ProjetStatisfootBundle:Equipe:view
    requirements:
        id: \d+

statisfoot_effectif:
    path:     /equipe/{id}/effectif
    defaults: 
        _controller: ProjetStatisfootBundle:Equipe:effectif
    requirements:
        id: \d+

statisfoot_joueur:
    path:     /joueur/{id}
    defaults: 
        _controller: ProjetStatisfootBundle:Joueur:view
    requirements:
        id: \d+ 

statisfoot_stat_joueur:
    path:     /joueur/{id}/stat
    defaults: 
        _controller: ProjetStatisfootBundle:Joueur:stat
    requirements:
        id: \d+

statisfoot_compet:
    path:     /compet/{id}
    defaults: 
        _controller: ProjetStatisfootBundle:Competition:view
    requirements:
        id: \d+

statisfoot_compte_journee:
    path:     /compet/{id}/{numJ}
    defaults: 
        _controller: ProjetStatisfootBundle:Competition:journee
    requirements:
        id: \d+
        numJ: \d+

