statisfoot_accueil:
    path:     /
    defaults: 
        _controller: ProjetStatisfootBundle:Match:index

statisfoot_accueil_manage:
    path:     /manage
    defaults: 
        _controller: ProjetStatisfootBundle:Match:index_manage

statisfoot_accueil_date:
    path:     /{date}
    defaults: 
        _controller: ProjetStatisfootBundle:Match:indexDate
    requirements:
        date: \d{10}

statisfoot_match:
    path:     /match/{id}
    defaults: 
        _controller: ProjetStatisfootBundle:Match:match_foot 
    requirements:
        id: \d+

statisfoot_manage_avant_match:
    path:     /manage/avant/match/{id}
    defaults: 
        _controller: ProjetStatisfootBundle:Match:avant_match 
    requirements:
        id: \d+

statisfoot_manage_match_encours:
    path:     /manage/match/encours/{id}
    defaults: 
        _controller: ProjetStatisfootBundle:Match:match_encours 
    requirements:
        id: \d+

statisfoot_manage_match_event:
    path:     /manage/match/event/{idM}/{idA}
    defaults: 
        _controller: ProjetStatisfootBundle:Match:match_event
    requirements:
        idM: \d+
        idA: \d+

statisfoot_club:
    path:     /club/{id}
    defaults: 
        _controller: ProjetStatisfootBundle:Equipe:club

statisfoot_liste_equipe:
    path:     /listeEquipe
    defaults: 
        _controller: ProjetStatisfootBundle:Equipe:listequipe

statisfoot_equipe:
    path:     /equipe/{id}
    defaults: 
        _controller: ProjetStatisfootBundle:Equipe:view
    requirements:
        id: \d+

statisfoot_manage_equipe:
    path:     /manage/equipe/{id}
    defaults: 
        _controller: ProjetStatisfootBundle:Equipe:manage_equipe
    requirements:
        id: \d+  

statisfoot_manage_joueur:
    path:     /manage/joueur/{id}
    defaults: 
        _controller: ProjetStatisfootBundle:Joueur:manage_joueur
    requirements:
        id: \d+

statisfoot_manage_joueur_ajout:
    path:     /manage/joueur/ajout
    defaults: 
        _controller: ProjetStatisfootBundle:Joueur:joueur_add

statisfoot_manage_joueur_mod:
    path:     /manage/joueur/mod/{id}
    defaults: 
        _controller: ProjetStatisfootBundle:Joueur:joueur_mod
    requirements:
        id: \d+

statisfoot_manage_joueur_sup:
    path:     /manage/joueur/sup/{id}
    defaults: 
        _controller: ProjetStatisfootBundle:Joueur:joueur_sup
    requirements:
        id: \d+

statisfoot_manage_joueur_remp:
    path:     /manage/joueur/remp/{idRt}/{idRe}
    defaults: 
        _controller: ProjetStatisfootBundle:Joueur:joueur_remp
    requirements:
        idRt: \d+
        idRe: \d+  

statisfoot_manage_joueur_but:
    path:     /manage/joueur/but/{idJ}/{idM}/{idB}/{idA}
    defaults: 
        _controller: ProjetStatisfootBundle:Joueur:joueur_but
    requirements:
        idJ: \d+
        idM: \d+
        idB: \d+
        idA: \d+

statisfoot_manage_joueur_passe:
    path:     /manage/joueur/passe/{idJ}/{idM}/{idP}
    defaults: 
        _controller: ProjetStatisfootBundle:Joueur:joueur_passe
    requirements:
        idJ: \d+
        idM: \d+
        idP: \d+  

statisfoot_manage_joueur_action:
    path:     /manage/joueur/action/{idJ}/{idM}/{idA}
    defaults: 
        _controller: ProjetStatisfootBundle:Joueur:joueur_action
    requirements:
        idJ: \d+
        idM: \d+
        idA: \d+ 

statisfoot_effectif:
    path:     /equipe/{id}/effectif
    defaults: 
        _controller: ProjetStatisfootBundle:Equipe:effectif
    requirements:
        id: \d+

statisfoot_joueur:
    path:     /joueur/{id}
    defaults: 
        _controller: ProjetStatisfootBundle:Joueur:view
    requirements:
        id: \d+ 

statisfoot_stat_joueur:
    path:     /joueur/{id}/stat
    defaults: 
        _controller: ProjetStatisfootBundle:Joueur:stat
    requirements:
        id: \d+

statisfoot_compet:
    path:     /compet/{id}
    defaults: 
        _controller: ProjetStatisfootBundle:Competition:view
    requirements:
        id: \d+

statisfoot_compte_journee:
    path:     /compet/{id}/{numJ}
    defaults: 
        _controller: ProjetStatisfootBundle:Competition:journee
    requirements:
        id: \d+
        numJ: \d+

